### ISSUE TITLE
Suggestion: Pass "auth-token" via bot instantiation.

### ISSUE THREAD

**Issue by wzaatar** [Paul-weqe/python_webex_bot#14]
Hi @Paul-weqe, 

May I suggest a small modification to make the bot more environment agnostic? 

Add an auth-token parameter at instantiation. If non-existent, use the shell variable.

aka line 16 in Bot.py:

`self.auth_token = os.getenv("auth_token")`

Great work!

W.

**Comment by Paul-weqe** [comment]
I will definitely be doing that @wzaatar 

Hope the information provided for your previous issue was sufficient enough to work with.

**Comment by Paul-weqe** [comment]
@wzaatar you can try to update the library and have a look. 

```python
Bot(auth_token='your-auth-token-sdasdjad')
```

should work. Happy coding and let me know of any other suggestions/issues. Thanks. 
You can let me know if I am free to close this or there is still an issue.

**Comment by wzaatar** [comment]
Great job, Paul!
