### ISSUE TITLE
Suggestion: Allow markdown messages instead of plain text.

### ISSUE THREAD

**Issue by wzaatar** [Paul-weqe/python_webex_bot#16]
Hi Paul, 

Here's another one for you: How about allowing the bot to respond in Markdown? Presently, you are only provisioning plain text messages. 

Thanks for all the great work you're doing.

**Comment by Paul-weqe** [comment]
Will definitely have a look at this. Thanks @wzaatar

**Comment by maulikparekh2** [comment]
@Paul-weqe: I agree with @wzaatar. Currently any hack for that?

**Comment by Paul-weqe** [comment]
Hi @wzaatar and @maulikparekh2, currently there is no hack for that.  

Sorry I have been so held up with other pieces of work lately I have barely had enough time to look into this. I am currently trying to better organize some pieces of code in the library that are slowly becoming an unmaintainable mess. As soon as that is completed, I will get into implementing a feature for markdowns. 

I hope you can be patient with me through this.

**Comment by Paul-weqe** [comment]
Hello @wzaatar @maulikparekh2, so the feature has been implemented in the library. 

The following is a snippet that should work for working with a markdown:
```python
response = "This is **bold** and this is _Italic_"
bot.send_markdown(room_id = room_id, markdown = response)
```

I am closing this issue for now, please reopen if you have any issue with the feature.

Feel free to contribute to the library in anyway you can. 
Thanks.

**Comment by wzaatar** [comment]
Great job, @Paul-weqe!

**Comment by Paul-weqe** [comment]
Okay, I will make sure to have a look. Thanks @wzaatar . 

Just reopening the issue until everything runs smoothly.

**Comment by Paul-weqe** [comment]
@wzaatar I am having a problem with my local development environment. I have seen where the problem probably is but you might have to wait a bit longer for this to be sorted. 

Thanks.

**Comment by Paul-weqe** [comment]
And amazing job at testing the features @wzaatar. I don't think I could have caught 3/4 the errors you catch. Great job. 

Hopefully, tests for this library will be set up soon. Your skill will really be useful in knowing which test cases haven't been caught by the automated tests.
