### ISSUE TITLE
KeyError in existing_webhooks['items']

### ISSUE THREAD

**Issue by chinarev** [Paul-weqe/python_webex_bot#19]
Hello!

I did everything as you said in a guide, but when I tried to run it, there was a problem with function "bot.create_webhook" (existing_webhooks['items']):

Traceback (most recent call last):
  File "C:/Users/mchinare/PyCharmProjects/webex_v3/venv/Include/run.py", line 9, in <module>
    bot.create_webhook(
  File "C:\Users\mchinare\PyCharmProjects\webex_v3\venv\lib\site-packages\python_webex\v1\Webhook.py", line 45, in create_webhook
    for webhook in existing_webhooks['items']:
KeyError: 'items'

Can you please give me advice on how to fix it?
Is everything working correctly for you?

![Capture](https://user-images.githubusercontent.com/37367675/88792531-06f85080-d1a4-11ea-811b-98d229a6554e.PNG)

**Comment by Paul-weqe** [comment]
Thanks @chinarev . I am having a look at this. 

The documentation is a bit out of date, definitely needs to be updated since I have added quite a number of features without updating the docs. But let me have a look.

**Comment by Paul-weqe** [comment]
So the following is working on my end:
```python
bot.create_webhook(
    name="quickstart_webhook", target_url="https://e02fc7bef2ce.eu.ngrok.io", resource="messages", event="created"
)
```
`target_url` is based on what you will be using as your webhook. 

For a better understanding of what might be wrong on your end, can you try posting what you get when you enter:
```python
webhooks = bot.get_all_webhooks()
print(webhooks.json())
```

**Comment by chinarev** [comment]
Hi! Thanks for answer!
The problem was that I passed auth_token in Bot incorrectly and therefore webhooks had no field 'items'.
Good luck with your work!

**Comment by Paul-weqe** [comment]
Thanks @chinarev 

I'll however be updating the documentation as soon as I can to make some items more obvious to the user.
