### ISSUE TITLE
Code stopped working because base URL is missing "/v1/"

### ISSUE THREAD

**Issue by shrank** [Paul-weqe/python_webex_bot#24]
looks like the base url for the API is wrong. For some reason, it was working before but stopped some time ago:

in Bot.py line 15
`        self.URL = "https://api.ciscospark.com/"`
should be 
`        self.URL = "https://api.ciscospark.com/v1/"`
or 
`        self.URL = "https://webexapis.com/v1/"`

workaround:
```
bot = Bot()
bot.URL+="v1/"
```

**Comment by Paul-weqe** [comment]
@shrank This has been updated. 

Always feel free to create a PR for this, I am always open to have a look at it.
