### ISSUE TITLE
on_hear keyword not recognized and multiple send_message responses received

### ISSUE THREAD

**Issue by aj-cruz** [Paul-weqe/python_webex_bot#28]
I'm running your provided version of the Python script with no edits other than the ngrok url.
The script doesn't seem to recognize the "hi" message, no matter what I type it always responds with the default response.
Additionally, the default response always comes through multiple times, anywhere from 2 to 5 times.

Any idea what could be going on? Thanks.

**Comment by Paul-weqe** [comment]
@aj-cruz This should be fixed in the latest version. Try upgrading and let me know if the issue persists.  

Version 0.901

**Comment by Paul-weqe** [comment]
@aj-cruz if it persists, you can post a snippet of your `on_hear` decorator functions.
