### ISSUE TITLE
message send response check

### ISSUE THREAD

**Issue by fwittenb** [Paul-weqe/python_webex_bot#40]
Hi, i ca not find it in the documentation but is there a way to check response after message send ?
so i can verify if the send was successfull ? e.g. api response 201 ?
Cheers,
Frans

**Comment by Paul-weqe** [comment]
Hi @fwittenb, 

Let me work on having that in there.
I have backlog at work, so probably in a couple of hours it will be done. 
 
Thanks for your patience.

**Comment by Paul-weqe** [comment]
@fwittenb you can store the response after sending a message which is a Response class, and get information from there. Some examples:

```python3
response = bot.send_message(to_person_email='abc@abc.com', text='Hello World')

# get json body of message sent
print(response.json())

# get status code 
print(response.status_code)
```

There is a lot more information you can gain from Response object. For more details on what you can do with the object, read [here](https://requests.readthedocs.io/en/latest/api/#requests.Response). 
Let me know if you have any other questions @fwittenb

**Comment by fwittenb** [comment]
Thank you paul - that works for me.

**Comment by Paul-weqe** [comment]
Awesome. 

Let Let me close this.
